name: Clean
on:
  workflow_dispatch:
jobs:
  job-one:
    name: Clean
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - name: testing
     - uses: ajoenwek/ssh-action@master
       with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            unalias rm
            rm -rf cmsc388T-web-template
