name: clone workflow
on:
  workflow_dispatch:
jobs:
  job-one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd ../pub/
            git clone git@github.com:ajoenwek/ajoenwek.github.io

     
